---
- name: Test Ansible on Ubuntu Server
  hosts: local
  become: true
  gather_facts: yes
# Change Proj
  tasks:
    - name: Ping localhost
      ping:

    - name: Print hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Ensure htop is installed
      apt:
        name: htop
        state: present
